### ISSUE TITLE
Implement retry backoff for GetConnector API calls

### ISSUE THREAD

**Issue by dstrates** [Mongey/terraform-provider-kafka-connect#151]
## Description

We're experiencing flaky `GetConnector` behavior due to API calls failing when brokers are rebalancing, particularly with Amazon MSK brokers. Although the client library seems to handle rebalances (see: [go-kafka-connect issue #3](https://github.com/ricardo-ch/go-kafka-connect/issues/3)), we could potentially implement safeguards to handle these cases better.

**Suggestion:** Implement retry backoff or a similar method to mitigate these issues. We could potentially use the retry mechanism outlined here: [Terraform SDK v2 retries and timeouts](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts#retry).

## Context

Amazon MSK brokers appear to frequently trigger automatic rebalances, causing the following error on `Terraform apply`:

```
Error: Get connector : {"error_code":500,"message":"Request cannot be completed because a rebalance is expected"}
```

**Comment by james-johnston-thumbtack** [comment]
We've also frequently seen this exact error when applying Terraform.  Attempting to reapply terraform results in one of two scenarios:

- The next plan shows nothing to do - it turns out everything was applied just fine.
- The next plan shows the resources as tainted.  However, untainting the resource shows that everything is actually just fine, and there is nothing to do.

Seems like there should be some sort of retry loop if the cluster is in the process of rebalancing.

The Connect cluster also logs a message like this:

```
{
  "exception": {
    "stacktrace": "org.apache.kafka.connect.runtime.distributed.RebalanceNeededException: Request cannot be completed because a rebalance is expected\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.checkRebalanceNeeded(DistributedHerder.java:2196)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$connectorInfo$5(DistributedHerder.java:837)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.runRequest(DistributedHerder.java:2240)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:470)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:371)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)",
    "exception_class": "org.apache.kafka.connect.runtime.distributed.RebalanceNeededException",
    "exception_message": "Request cannot be completed because a rebalance is expected"
  },
  "source_host": "57d2ef9400ba",
  "method": "toResponse",
  "level": "ERROR",
  "message": "Uncaught exception in REST call to /connectors/my_connector",
  "mdc": {},
  "@timestamp": "2025-02-07T20:13:01.109Z",
  "file": "ConnectExceptionMapper.java",
  "line_number": "64",
  "thread_name": "qtp1335479568-15164",
  "@version": 1,
  "logger_name": "org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper",
  "class": "org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper"
}
```
Stack trace reformatted:
```
org.apache.kafka.connect.runtime.distributed.RebalanceNeededException: Request cannot be completed because a rebalance is expected
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.checkRebalanceNeeded(DistributedHerder.java:2196)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$connectorInfo$5(DistributedHerder.java:837)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.runRequest(DistributedHerder.java:2240)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:470)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:371)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

(this is on a self-hosted Connect using `FROM confluentinc/cp-kafka-connect:7.6.1` docker image)
